"""added isAdmin col

Revision ID: 008391b29931
Revises: a412fa0b5161
Create Date: 2020-04-15 18:54:07.073145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008391b29931'
down_revision = 'a412fa0b5161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###
