"""update games table with current player index

Revision ID: 2dc71fd2a1f3
Revises: ffd47b4de755
Create Date: 2020-04-09 14:03:07.898914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc71fd2a1f3'
down_revision = 'ffd47b4de755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('currentPlayerIndex', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'currentPlayerIndex')
    # ### end Alembic commands ###
