"""add users table

Revision ID: 378ea022dffa
Revises: 81c11d54573a
Create Date: 2020-04-08 13:06:08.378352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378ea022dffa'
down_revision = '81c11d54573a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_game_code', table_name='game')
    op.drop_table('game')
    op.create_index(op.f('ix_games_code'), 'games', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_code'), table_name='games')
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_code', 'game', ['code'], unique=1)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
