"""add cards table

Revision ID: ffd47b4de755
Revises: 378ea022dffa
Create Date: 2020-04-09 13:49:29.764357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd47b4de755'
down_revision = '378ea022dffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suit', sa.String(length=1), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=3), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
